version: 2.1
executors:
  android:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
jobs:
  build:
    executor: android
    steps:
      - checkout:
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

          -run : 
          name: chmod permissions 
          command : sudo chmod ./gradlew
      - run:
          
          name: download dependencies 
        command:  ./gradlew andriodDependencies

        steps:
  - checkout:
  - run:
      name: Build Project
      command: ./gradlew build



      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle/caches
      - run:
          name: Run tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: test-reports
      - store_test_results:
          path: app/build/test-results
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
